
echo Setting up, finding bridge IP and creating docker-compose.yml

BRIDGE_IP=$( ip addr | grep -A2 docker0: | grep inet | xargs | cut -f2 -d' ' | cut -f1 -d/ )

if [ -z $BRIDGE_IP ]
then
	BRIDGE_IP=$1
fi

if [ -z $BRIDGE_IP ]
then
	echo Sorry, could not find BRIDGE_IP, please re-run setup with the correct ip, e.g.:
	echo $ mca setup 172.17.0.1
	exit 1
fi

if [ -f docker-compose.yml ]
then
  chmod u+w docker-compose.yml
fi
echo "# DO NOT EDIT " > docker-compose.yml
echo "# generated by 'mca setup' - edit docker-compose.yml.tmpl instead" >> docker-compose.yml
cat docker-compose.yml.tmpl | sed "s/<%SKYDNS%>/$BRIDGE_IP/" >> docker-compose.yml
chmod a-w docker-compose.yml
