#!/bin/bash

cd "`dirname $0`"

set -e

ROOT="etc-amc"

dirs=`ls -F $ROOT | grep /`


if [ "$1" = "" ]
then
	echo
	echo "        amc - Alfresco Multi Container"
	echo "        ------------------------------"
	echo 
	echo The following commands are available:
	echo
	for dir in $dirs
	do
		echo  "amc `cat $ROOT/$dir/CMD` - `cat $ROOT/$dir/INFO`"
	done
	echo
elif [ "$1" == "edit" ]
then
  for dir in $dirs
	do
		if [ -f $ROOT/$dir/CMD -a "$(cat $ROOT/$dir/CMD)" == $2 ]
		then
			if [ -n $2 ]
			then
				${EDITOR:-vi} $ROOT/$dir/$2
			else
	    	${EDITOR:-vi} $ROOT/$dir/*
			fi
		fi
	done
elif [ "$1" == "help" ]
then
	if [ -z "$2" ]
	then
    $0
	else
		for dir in $dirs
		do
			if [ -f $ROOT/$dir/CMD -a "$(cat $ROOT/$dir/CMD)" == $2 ]
			then
				echo
				echo "amc $(cat $ROOT/$dir/CMD)"
				echo
				cat $ROOT/$dir/HELP
				echo
			fi
		done
	fi
else
  # search for the command 
	for dir in $dirs
	do
    if [ -f $ROOT/$dir/CMD ]
		then
			if [ "$( cat $ROOT/$dir/CMD )" == "$1" ]
			then
				shift
				echo -e "--==] \t amc `cat $ROOT/$dir/CMD` \t [==--"
				echo
				bash $ROOT/$dir/do.sh $*
			fi
		fi
	done
fi
