FROM marsbard/base

RUN apt-get update && apt-get -y install apache2

RUN a2enmod proxy_ajp ssl

COPY files/localhost.conf /etc/apache2/sites-enabled

VOLUME /data
RUN mkdir -p /data/lock /data/run /var/www/localhost

ENV APACHE_LOCK_DIR=/data/lock APACHE_PID_FILE=/data/pidfile APACHE_RUN_USER=nobody 
ENV APACHE_RUN_GROUP=nogroup APACHE_LOG_DIR=/var/log/apache2 APACHE_RUN_DIR=/data/run

COPY files/entrypoint.sh /
RUN chmod +x /entrypoint.sh

ENTRYPOINT /entrypoint.sh
