FROM marsbard/tomcat

COPY files/tmp/share.war /tomcat/webapps/share.war

COPY files/share-config-custom.xml /tomcat/shared/classes/alfresco/web-extension/share-config-custom.xml

COPY files/log4j.properties /tomcat/shared/classes/alfresco/extension/log4j.properties


