#!/bin/bash

if [ ! -f /usr/local/apache2/conf/httpd.conf ]
then
	perl -p -i -e 's/\$\{([^}]+)\}/defined $ENV{$1} ? $ENV{$1} : $&/eg' < /tmp/httpd.conf.tpl > /usr/local/apache2/conf/httpd.conf
fi

echo Removing old PID files
# Apache gets grumpy about PID files pre-existing 
rm -f /usr/local/apache2/logs/httpd.pid

echo Removing logs older than 20 days
find /usr/local/apache2/logs/*.log.* -mtime +20 -type f -delete

echo Rotating old logs 
NOW=`date +%s`
for file in /usr/local/apache2/logs/*.log
do
	mv $file $file.$NOW
done

echo Setting up /etc/ssl
if [ ! -f /etc/ssl/openssl.cnf ]
then
	mkdir -p /etc/ssl
  cp -r /etc/ssl.orig/* /etc/ssl
fi


echo Generating certs if necessary
/generate-certs.sh

echo Running httpd
exec httpd -DFOREGROUND
