FROM marsbard/tomcat

COPY alfresco.war /tomcat/webapps
COPY server.xml /tomcat/conf/server.xml
COPY catalina.properties /tomcat/conf/catalina.properties
COPY alfresco-global.properties /tomcat/shared/classes/alfresco-global.properties

